### ISSUE TITLE
[Bug]  flags "is already declared in the upper scope" for enum declaration

### ISSUE THREAD

**Issue by dayuy** [yuntijs/yunti-lint#2]
### 💻 系统环境 | Operating System

macOS

### 🐛 问题描述 | Bug Description

Linting a TypeScript file that contains only the following line

```
export enum PanelFormat {
  short = 'short',
  percent = 'percent',
}
```
flags the error 'PanelFormat' is already declared in the upper scope.

### 🚦 期望结果 | Expected Behavior

No error on a unique enum.

**Comment by Carrotzpc** [comment]
fixed in https://github.com/yuntijs/yunti-lint/commit/cd4a077f3986fcf275b2f3f6d0234fe79b6f428a , please use v1.5.0
