### ISSUE TITLE
[Request] support `eslint-plugin-react-hooks`

### ISSUE THREAD

**Issue by dayuy** [yuntijs/yunti-lint#3]
### 🥰 需求描述 | Feature Description

EsLint 希望支持 React Hooks，参考 [Linting](https://zh-hans.react.dev/learn/editor-setup#linting)

### 🧐 解决方案 | Proposed Solution

1. `pnpm install eslint-plugin-react-hooks -D`
2. .eslintrc.js
```
{
  "plugins": [
    // ...
    "react-hooks"
  ],
  "rules": {
    // ...
    "react-hooks/rules-of-hooks": "error", // 检查 Hook 的规则
    "react-hooks/exhaustive-deps": "warn" // 检查 effect 的依赖
  }
}
```

**Comment by Carrotzpc** [comment]
fixed in f52c00ed057c949401393851a393d414ae66e239, and released in [@yuntijs/lint@1.7.0](https://www.npmjs.com/package/@yuntijs/lint/v/1.7.0)
